# Generated by Django 2.1.7 on 2019-02-15 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singh', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Student',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
